### PR TITLE
feat: add org README

### PR DESCRIPTION
**Pull request by Okabe-Junya**
## Feature Descriptions

- add README for our organization 
    - See [Customizing your organization's profile](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile) for more details

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
@ciaran-regan-ie 

I'm not at good at writing English, so if you have enough time to review, I'm appreciate if you will review :)

If you have any ideas to improve this doc, feel free to edit!!

**Comment by Okabe-Junya** [comment]
- preview: https://github.com/tsukuba-websci/.github/blob/e65e8af69ba5246b6d0fd8f53dc4452aa0c4a410/profile/README.md

**Comment by Okabe-Junya** [comment]
and if you lgtm, please merge

**Comment by ciaran-regan-ie** [comment]
LGTM!!

**Comment by Okabe-Junya** [comment]
thank you!!

**Pull request merged**
